namespace CarRentalSystem2.Views
{
    partial class InquiryPage
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(InquiryPage));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.txtSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dtgAvailableCars = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnClear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnInquire = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel11 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtContact = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtLastName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnRent = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtMiddleName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cmbCarId = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtFirstName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cmbGender = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtModel = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtBrand = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dtgAvailableCars)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 15;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.txtSearch);
            this.bunifuPanel2.Controls.Add(this.dtgAvailableCars);
            this.bunifuPanel2.Controls.Add(this.pictureBox1);
            this.bunifuPanel2.Location = new System.Drawing.Point(12, 312);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(956, 396);
            this.bunifuPanel2.TabIndex = 5;
            // 
            // txtSearch
            // 
            this.txtSearch.AcceptsReturn = false;
            this.txtSearch.AcceptsTab = false;
            this.txtSearch.AnimationSpeed = 200;
            this.txtSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSearch.AutoSizeHeight = true;
            this.txtSearch.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSearch.BackgroundImage")));
            this.txtSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSearch.BorderColorIdle = System.Drawing.Color.DeepSkyBlue;
            this.txtSearch.BorderRadius = 10;
            this.txtSearch.BorderThickness = 2;
            this.txtSearch.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSearch.DefaultText = "";
            this.txtSearch.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtSearch.HideSelection = true;
            this.txtSearch.IconLeft = null;
            this.txtSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.IconPadding = 10;
            this.txtSearch.IconRight = null;
            this.txtSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.Lines = new string[0];
            this.txtSearch.Location = new System.Drawing.Point(67, 23);
            this.txtSearch.MaxLength = 32767;
            this.txtSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSearch.Modified = false;
            this.txtSearch.Multiline = false;
            this.txtSearch.Name = "txtSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.White;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties2.FillColor = System.Drawing.Color.Transparent;
            stateProperties2.ForeColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnIdleState = stateProperties4;
            this.txtSearch.Padding = new System.Windows.Forms.Padding(3);
            this.txtSearch.PasswordChar = '\0';
            this.txtSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSearch.PlaceholderText = "";
            this.txtSearch.ReadOnly = false;
            this.txtSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSearch.SelectedText = "";
            this.txtSearch.SelectionLength = 0;
            this.txtSearch.SelectionStart = 0;
            this.txtSearch.ShortcutsEnabled = true;
            this.txtSearch.Size = new System.Drawing.Size(243, 33);
            this.txtSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSearch.TabIndex = 36;
            this.txtSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSearch.TextMarginBottom = 0;
            this.txtSearch.TextMarginLeft = 3;
            this.txtSearch.TextMarginTop = 1;
            this.txtSearch.TextPlaceholder = "";
            this.txtSearch.UseSystemPasswordChar = false;
            this.txtSearch.WordWrap = true;
            // 
            // dtgAvailableCars
            // 
            this.dtgAvailableCars.AllowCustomTheming = true;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.dtgAvailableCars.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dtgAvailableCars.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dtgAvailableCars.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(51)))), ((int)(((byte)(73)))));
            this.dtgAvailableCars.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtgAvailableCars.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtgAvailableCars.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DeepSkyBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.DeepSkyBlue;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtgAvailableCars.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dtgAvailableCars.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dtgAvailableCars.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.dtgAvailableCars.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgAvailableCars.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.dtgAvailableCars.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgAvailableCars.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dtgAvailableCars.CurrentTheme.BackColor = System.Drawing.Color.DeepSkyBlue;
            this.dtgAvailableCars.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgAvailableCars.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DeepSkyBlue;
            this.dtgAvailableCars.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dtgAvailableCars.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.dtgAvailableCars.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dtgAvailableCars.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dtgAvailableCars.CurrentTheme.Name = null;
            this.dtgAvailableCars.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dtgAvailableCars.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgAvailableCars.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgAvailableCars.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgAvailableCars.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dtgAvailableCars.DefaultCellStyle = dataGridViewCellStyle3;
            this.dtgAvailableCars.EnableHeadersVisualStyles = false;
            this.dtgAvailableCars.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgAvailableCars.HeaderBackColor = System.Drawing.Color.DeepSkyBlue;
            this.dtgAvailableCars.HeaderBgColor = System.Drawing.Color.Empty;
            this.dtgAvailableCars.HeaderForeColor = System.Drawing.Color.DeepSkyBlue;
            this.dtgAvailableCars.Location = new System.Drawing.Point(19, 62);
            this.dtgAvailableCars.Name = "dtgAvailableCars";
            this.dtgAvailableCars.RowHeadersVisible = false;
            this.dtgAvailableCars.RowHeadersWidth = 51;
            this.dtgAvailableCars.RowTemplate.Height = 40;
            this.dtgAvailableCars.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dtgAvailableCars.Size = new System.Drawing.Size(916, 321);
            this.dtgAvailableCars.TabIndex = 19;
            this.dtgAvailableCars.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.pictureBox1.BackgroundImage = global::CarRentalSystem2.Properties.Resources.search;
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.pictureBox1.Location = new System.Drawing.Point(19, 23);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(42, 33);
            this.pictureBox1.TabIndex = 18;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 15;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btnClear);
            this.bunifuPanel1.Controls.Add(this.btnInquire);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel11);
            this.bunifuPanel1.Controls.Add(this.txtContact);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel10);
            this.bunifuPanel1.Controls.Add(this.txtLastName);
            this.bunifuPanel1.Controls.Add(this.btnRent);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel9);
            this.bunifuPanel1.Controls.Add(this.txtMiddleName);
            this.bunifuPanel1.Controls.Add(this.cmbCarId);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel5);
            this.bunifuPanel1.Controls.Add(this.txtFirstName);
            this.bunifuPanel1.Controls.Add(this.cmbGender);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Controls.Add(this.txtModel);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.txtBrand);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Location = new System.Drawing.Point(12, 12);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(956, 294);
            this.bunifuPanel1.TabIndex = 4;
            // 
            // btnClear
            // 
            this.btnClear.AllowAnimations = true;
            this.btnClear.AllowMouseEffects = true;
            this.btnClear.AllowToggling = false;
            this.btnClear.AnimationSpeed = 200;
            this.btnClear.AutoGenerateColors = false;
            this.btnClear.AutoRoundBorders = false;
            this.btnClear.AutoSizeLeftIcon = true;
            this.btnClear.AutoSizeRightIcon = true;
            this.btnClear.BackColor = System.Drawing.Color.Transparent;
            this.btnClear.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.btnClear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClear.BackgroundImage")));
            this.btnClear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClear.ButtonText = "Clear";
            this.btnClear.ButtonTextMarginLeft = 0;
            this.btnClear.ColorContrastOnClick = 45;
            this.btnClear.ColorContrastOnHover = 45;
            this.btnClear.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnClear.CustomizableEdges = borderEdges1;
            this.btnClear.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClear.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClear.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClear.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.btnClear.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClear.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.btnClear.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClear.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClear.IconLeftPadding = new System.Windows.Forms.Padding(15, 0, 3, 3);
            this.btnClear.IconMarginLeft = 11;
            this.btnClear.IconPadding = 10;
            this.btnClear.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClear.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClear.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClear.IconSize = 25;
            this.btnClear.IdleBorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btnClear.IdleBorderRadius = 10;
            this.btnClear.IdleBorderThickness = 2;
            this.btnClear.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.btnClear.IdleIconLeftImage = null;
            this.btnClear.IdleIconRightImage = null;
            this.btnClear.IndicateFocus = false;
            this.btnClear.Location = new System.Drawing.Point(792, 200);
            this.btnClear.Name = "btnClear";
            this.btnClear.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClear.OnDisabledState.BorderRadius = 10;
            this.btnClear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClear.OnDisabledState.BorderThickness = 2;
            this.btnClear.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClear.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClear.OnDisabledState.IconLeftImage = null;
            this.btnClear.OnDisabledState.IconRightImage = null;
            this.btnClear.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClear.onHoverState.BorderRadius = 10;
            this.btnClear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClear.onHoverState.BorderThickness = 2;
            this.btnClear.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClear.onHoverState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.btnClear.onHoverState.IconLeftImage = null;
            this.btnClear.onHoverState.IconRightImage = null;
            this.btnClear.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btnClear.OnIdleState.BorderRadius = 10;
            this.btnClear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClear.OnIdleState.BorderThickness = 2;
            this.btnClear.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.btnClear.OnIdleState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.btnClear.OnIdleState.IconLeftImage = null;
            this.btnClear.OnIdleState.IconRightImage = null;
            this.btnClear.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClear.OnPressedState.BorderRadius = 10;
            this.btnClear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnClear.OnPressedState.BorderThickness = 2;
            this.btnClear.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClear.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClear.OnPressedState.IconLeftImage = null;
            this.btnClear.OnPressedState.IconRightImage = null;
            this.btnClear.Size = new System.Drawing.Size(143, 57);
            this.btnClear.TabIndex = 31;
            this.btnClear.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClear.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClear.TextMarginLeft = 0;
            this.btnClear.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClear.UseDefaultRadiusAndThickness = true;
            // 
            // btnInquire
            // 
            this.btnInquire.AllowAnimations = true;
            this.btnInquire.AllowMouseEffects = true;
            this.btnInquire.AllowToggling = false;
            this.btnInquire.AnimationSpeed = 200;
            this.btnInquire.AutoGenerateColors = false;
            this.btnInquire.AutoRoundBorders = false;
            this.btnInquire.AutoSizeLeftIcon = true;
            this.btnInquire.AutoSizeRightIcon = true;
            this.btnInquire.BackColor = System.Drawing.Color.Transparent;
            this.btnInquire.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.btnInquire.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInquire.BackgroundImage")));
            this.btnInquire.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInquire.ButtonText = "Inquire";
            this.btnInquire.ButtonTextMarginLeft = 0;
            this.btnInquire.ColorContrastOnClick = 45;
            this.btnInquire.ColorContrastOnHover = 45;
            this.btnInquire.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnInquire.CustomizableEdges = borderEdges2;
            this.btnInquire.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInquire.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInquire.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInquire.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInquire.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.btnInquire.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnInquire.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.btnInquire.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInquire.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnInquire.IconLeftPadding = new System.Windows.Forms.Padding(10, 0, 3, 3);
            this.btnInquire.IconMarginLeft = 11;
            this.btnInquire.IconPadding = 10;
            this.btnInquire.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnInquire.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnInquire.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnInquire.IconSize = 25;
            this.btnInquire.IdleBorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btnInquire.IdleBorderRadius = 10;
            this.btnInquire.IdleBorderThickness = 2;
            this.btnInquire.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.btnInquire.IdleIconLeftImage = global::CarRentalSystem2.Properties.Resources.inquire;
            this.btnInquire.IdleIconRightImage = null;
            this.btnInquire.IndicateFocus = false;
            this.btnInquire.Location = new System.Drawing.Point(458, 200);
            this.btnInquire.Name = "btnInquire";
            this.btnInquire.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInquire.OnDisabledState.BorderRadius = 10;
            this.btnInquire.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInquire.OnDisabledState.BorderThickness = 2;
            this.btnInquire.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInquire.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInquire.OnDisabledState.IconLeftImage = null;
            this.btnInquire.OnDisabledState.IconRightImage = null;
            this.btnInquire.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnInquire.onHoverState.BorderRadius = 10;
            this.btnInquire.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInquire.onHoverState.BorderThickness = 2;
            this.btnInquire.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnInquire.onHoverState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.btnInquire.onHoverState.IconLeftImage = null;
            this.btnInquire.onHoverState.IconRightImage = null;
            this.btnInquire.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btnInquire.OnIdleState.BorderRadius = 10;
            this.btnInquire.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInquire.OnIdleState.BorderThickness = 2;
            this.btnInquire.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.btnInquire.OnIdleState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.btnInquire.OnIdleState.IconLeftImage = global::CarRentalSystem2.Properties.Resources.inquire;
            this.btnInquire.OnIdleState.IconRightImage = null;
            this.btnInquire.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnInquire.OnPressedState.BorderRadius = 10;
            this.btnInquire.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInquire.OnPressedState.BorderThickness = 2;
            this.btnInquire.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnInquire.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnInquire.OnPressedState.IconLeftImage = null;
            this.btnInquire.OnPressedState.IconRightImage = null;
            this.btnInquire.Size = new System.Drawing.Size(143, 57);
            this.btnInquire.TabIndex = 30;
            this.btnInquire.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnInquire.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnInquire.TextMarginLeft = 0;
            this.btnInquire.TextPadding = new System.Windows.Forms.Padding(25, 0, 0, 0);
            this.btnInquire.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel11
            // 
            this.bunifuLabel11.AllowParentOverrides = false;
            this.bunifuLabel11.AutoEllipsis = false;
            this.bunifuLabel11.CursorType = null;
            this.bunifuLabel11.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel11.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.bunifuLabel11.Location = new System.Drawing.Point(91, 224);
            this.bunifuLabel11.Name = "bunifuLabel11";
            this.bunifuLabel11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel11.Size = new System.Drawing.Size(77, 28);
            this.bunifuLabel11.TabIndex = 29;
            this.bunifuLabel11.Text = "Contact :";
            this.bunifuLabel11.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel11.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtContact
            // 
            this.txtContact.AcceptsReturn = false;
            this.txtContact.AcceptsTab = false;
            this.txtContact.AnimationSpeed = 200;
            this.txtContact.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtContact.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtContact.AutoSizeHeight = true;
            this.txtContact.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtContact.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtContact.BackgroundImage")));
            this.txtContact.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtContact.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtContact.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtContact.BorderColorIdle = System.Drawing.Color.DeepSkyBlue;
            this.txtContact.BorderRadius = 10;
            this.txtContact.BorderThickness = 2;
            this.txtContact.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtContact.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtContact.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContact.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtContact.DefaultText = "";
            this.txtContact.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtContact.HideSelection = true;
            this.txtContact.IconLeft = null;
            this.txtContact.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContact.IconPadding = 10;
            this.txtContact.IconRight = null;
            this.txtContact.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContact.Lines = new string[0];
            this.txtContact.Location = new System.Drawing.Point(193, 224);
            this.txtContact.MaxLength = 32767;
            this.txtContact.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtContact.Modified = false;
            this.txtContact.Multiline = false;
            this.txtContact.Name = "txtContact";
            stateProperties5.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.White;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContact.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties6.FillColor = System.Drawing.Color.Transparent;
            stateProperties6.ForeColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtContact.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContact.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContact.OnIdleState = stateProperties8;
            this.txtContact.Padding = new System.Windows.Forms.Padding(3);
            this.txtContact.PasswordChar = '\0';
            this.txtContact.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtContact.PlaceholderText = "Enter Contact No";
            this.txtContact.ReadOnly = false;
            this.txtContact.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtContact.SelectedText = "";
            this.txtContact.SelectionLength = 0;
            this.txtContact.SelectionStart = 0;
            this.txtContact.ShortcutsEnabled = true;
            this.txtContact.Size = new System.Drawing.Size(216, 33);
            this.txtContact.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtContact.TabIndex = 28;
            this.txtContact.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtContact.TextMarginBottom = 0;
            this.txtContact.TextMarginLeft = 3;
            this.txtContact.TextMarginTop = 1;
            this.txtContact.TextPlaceholder = "Enter Contact No";
            this.txtContact.UseSystemPasswordChar = false;
            this.txtContact.WordWrap = true;
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel10.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.bunifuLabel10.Location = new System.Drawing.Point(71, 127);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(100, 28);
            this.bunifuLabel10.TabIndex = 27;
            this.bunifuLabel10.Text = "Last Name :";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtLastName
            // 
            this.txtLastName.AcceptsReturn = false;
            this.txtLastName.AcceptsTab = false;
            this.txtLastName.AnimationSpeed = 200;
            this.txtLastName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLastName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLastName.AutoSizeHeight = true;
            this.txtLastName.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtLastName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLastName.BackgroundImage")));
            this.txtLastName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtLastName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLastName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtLastName.BorderColorIdle = System.Drawing.Color.DeepSkyBlue;
            this.txtLastName.BorderRadius = 10;
            this.txtLastName.BorderThickness = 2;
            this.txtLastName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtLastName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLastName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLastName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtLastName.DefaultText = "";
            this.txtLastName.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtLastName.HideSelection = true;
            this.txtLastName.IconLeft = null;
            this.txtLastName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLastName.IconPadding = 10;
            this.txtLastName.IconRight = null;
            this.txtLastName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLastName.Lines = new string[0];
            this.txtLastName.Location = new System.Drawing.Point(193, 126);
            this.txtLastName.MaxLength = 32767;
            this.txtLastName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLastName.Modified = false;
            this.txtLastName.Multiline = false;
            this.txtLastName.Name = "txtLastName";
            stateProperties9.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.White;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLastName.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties10.FillColor = System.Drawing.Color.Transparent;
            stateProperties10.ForeColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLastName.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLastName.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLastName.OnIdleState = stateProperties12;
            this.txtLastName.Padding = new System.Windows.Forms.Padding(3);
            this.txtLastName.PasswordChar = '\0';
            this.txtLastName.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtLastName.PlaceholderText = "Enter Last Name";
            this.txtLastName.ReadOnly = false;
            this.txtLastName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLastName.SelectedText = "";
            this.txtLastName.SelectionLength = 0;
            this.txtLastName.SelectionStart = 0;
            this.txtLastName.ShortcutsEnabled = true;
            this.txtLastName.Size = new System.Drawing.Size(216, 33);
            this.txtLastName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtLastName.TabIndex = 26;
            this.txtLastName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLastName.TextMarginBottom = 0;
            this.txtLastName.TextMarginLeft = 3;
            this.txtLastName.TextMarginTop = 1;
            this.txtLastName.TextPlaceholder = "Enter Last Name";
            this.txtLastName.UseSystemPasswordChar = false;
            this.txtLastName.WordWrap = true;
            // 
            // btnRent
            // 
            this.btnRent.AllowAnimations = true;
            this.btnRent.AllowMouseEffects = true;
            this.btnRent.AllowToggling = false;
            this.btnRent.AnimationSpeed = 200;
            this.btnRent.AutoGenerateColors = false;
            this.btnRent.AutoRoundBorders = false;
            this.btnRent.AutoSizeLeftIcon = true;
            this.btnRent.AutoSizeRightIcon = true;
            this.btnRent.BackColor = System.Drawing.Color.Transparent;
            this.btnRent.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.btnRent.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRent.BackgroundImage")));
            this.btnRent.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRent.ButtonText = "Rent";
            this.btnRent.ButtonTextMarginLeft = 0;
            this.btnRent.ColorContrastOnClick = 45;
            this.btnRent.ColorContrastOnHover = 45;
            this.btnRent.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnRent.CustomizableEdges = borderEdges3;
            this.btnRent.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRent.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRent.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRent.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRent.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Idle;
            this.btnRent.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRent.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.btnRent.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRent.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRent.IconLeftPadding = new System.Windows.Forms.Padding(15, 0, 3, 3);
            this.btnRent.IconMarginLeft = 11;
            this.btnRent.IconPadding = 10;
            this.btnRent.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRent.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRent.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRent.IconSize = 25;
            this.btnRent.IdleBorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btnRent.IdleBorderRadius = 10;
            this.btnRent.IdleBorderThickness = 2;
            this.btnRent.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.btnRent.IdleIconLeftImage = global::CarRentalSystem2.Properties.Resources.carrent;
            this.btnRent.IdleIconRightImage = null;
            this.btnRent.IndicateFocus = false;
            this.btnRent.Location = new System.Drawing.Point(625, 200);
            this.btnRent.Name = "btnRent";
            this.btnRent.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRent.OnDisabledState.BorderRadius = 10;
            this.btnRent.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRent.OnDisabledState.BorderThickness = 2;
            this.btnRent.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRent.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRent.OnDisabledState.IconLeftImage = null;
            this.btnRent.OnDisabledState.IconRightImage = null;
            this.btnRent.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRent.onHoverState.BorderRadius = 10;
            this.btnRent.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRent.onHoverState.BorderThickness = 2;
            this.btnRent.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRent.onHoverState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.btnRent.onHoverState.IconLeftImage = null;
            this.btnRent.onHoverState.IconRightImage = null;
            this.btnRent.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btnRent.OnIdleState.BorderRadius = 10;
            this.btnRent.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRent.OnIdleState.BorderThickness = 2;
            this.btnRent.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.btnRent.OnIdleState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.btnRent.OnIdleState.IconLeftImage = global::CarRentalSystem2.Properties.Resources.carrent;
            this.btnRent.OnIdleState.IconRightImage = null;
            this.btnRent.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRent.OnPressedState.BorderRadius = 10;
            this.btnRent.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRent.OnPressedState.BorderThickness = 2;
            this.btnRent.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRent.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRent.OnPressedState.IconLeftImage = null;
            this.btnRent.OnPressedState.IconRightImage = null;
            this.btnRent.Size = new System.Drawing.Size(143, 57);
            this.btnRent.TabIndex = 14;
            this.btnRent.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRent.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRent.TextMarginLeft = 0;
            this.btnRent.TextPadding = new System.Windows.Forms.Padding(25, 0, 0, 0);
            this.btnRent.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel9.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.bunifuLabel9.Location = new System.Drawing.Point(43, 76);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(128, 28);
            this.bunifuLabel9.TabIndex = 25;
            this.bunifuLabel9.Text = "Middle Name :";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtMiddleName
            // 
            this.txtMiddleName.AcceptsReturn = false;
            this.txtMiddleName.AcceptsTab = false;
            this.txtMiddleName.AnimationSpeed = 200;
            this.txtMiddleName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMiddleName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMiddleName.AutoSizeHeight = true;
            this.txtMiddleName.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtMiddleName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMiddleName.BackgroundImage")));
            this.txtMiddleName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMiddleName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMiddleName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMiddleName.BorderColorIdle = System.Drawing.Color.DeepSkyBlue;
            this.txtMiddleName.BorderRadius = 10;
            this.txtMiddleName.BorderThickness = 2;
            this.txtMiddleName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtMiddleName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMiddleName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMiddleName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMiddleName.DefaultText = "";
            this.txtMiddleName.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtMiddleName.HideSelection = true;
            this.txtMiddleName.IconLeft = null;
            this.txtMiddleName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMiddleName.IconPadding = 10;
            this.txtMiddleName.IconRight = null;
            this.txtMiddleName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMiddleName.Lines = new string[0];
            this.txtMiddleName.Location = new System.Drawing.Point(193, 76);
            this.txtMiddleName.MaxLength = 32767;
            this.txtMiddleName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMiddleName.Modified = false;
            this.txtMiddleName.Multiline = false;
            this.txtMiddleName.Name = "txtMiddleName";
            stateProperties13.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.White;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMiddleName.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties14.FillColor = System.Drawing.Color.Transparent;
            stateProperties14.ForeColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMiddleName.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMiddleName.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMiddleName.OnIdleState = stateProperties16;
            this.txtMiddleName.Padding = new System.Windows.Forms.Padding(3);
            this.txtMiddleName.PasswordChar = '\0';
            this.txtMiddleName.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtMiddleName.PlaceholderText = "Enter Middle Name";
            this.txtMiddleName.ReadOnly = false;
            this.txtMiddleName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMiddleName.SelectedText = "";
            this.txtMiddleName.SelectionLength = 0;
            this.txtMiddleName.SelectionStart = 0;
            this.txtMiddleName.ShortcutsEnabled = true;
            this.txtMiddleName.Size = new System.Drawing.Size(216, 33);
            this.txtMiddleName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMiddleName.TabIndex = 24;
            this.txtMiddleName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMiddleName.TextMarginBottom = 0;
            this.txtMiddleName.TextMarginLeft = 3;
            this.txtMiddleName.TextMarginTop = 1;
            this.txtMiddleName.TextPlaceholder = "Enter Middle Name";
            this.txtMiddleName.UseSystemPasswordChar = false;
            this.txtMiddleName.WordWrap = true;
            // 
            // cmbCarId
            // 
            this.cmbCarId.BackColor = System.Drawing.Color.Transparent;
            this.cmbCarId.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.cmbCarId.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.cmbCarId.BorderRadius = 5;
            this.cmbCarId.Color = System.Drawing.Color.DeepSkyBlue;
            this.cmbCarId.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbCarId.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbCarId.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbCarId.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbCarId.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbCarId.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbCarId.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbCarId.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbCarId.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCarId.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbCarId.FillDropDown = true;
            this.cmbCarId.FillIndicator = false;
            this.cmbCarId.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbCarId.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cmbCarId.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.cmbCarId.FormattingEnabled = true;
            this.cmbCarId.Icon = null;
            this.cmbCarId.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbCarId.IndicatorColor = System.Drawing.Color.DeepSkyBlue;
            this.cmbCarId.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbCarId.IndicatorThickness = 2;
            this.cmbCarId.IsDropdownOpened = false;
            this.cmbCarId.ItemBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.cmbCarId.ItemBorderColor = System.Drawing.Color.DeepSkyBlue;
            this.cmbCarId.ItemForeColor = System.Drawing.Color.DeepSkyBlue;
            this.cmbCarId.ItemHeight = 26;
            this.cmbCarId.ItemHighLightColor = System.Drawing.Color.SkyBlue;
            this.cmbCarId.ItemHighLightForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.cmbCarId.ItemTopMargin = 3;
            this.cmbCarId.Location = new System.Drawing.Point(593, 27);
            this.cmbCarId.Name = "cmbCarId";
            this.cmbCarId.Size = new System.Drawing.Size(216, 32);
            this.cmbCarId.TabIndex = 17;
            this.cmbCarId.Text = null;
            this.cmbCarId.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbCarId.TextLeftMargin = 5;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.bunifuLabel5.Location = new System.Drawing.Point(68, 25);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(103, 28);
            this.bunifuLabel5.TabIndex = 10;
            this.bunifuLabel5.Text = "First Name : ";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtFirstName
            // 
            this.txtFirstName.AcceptsReturn = false;
            this.txtFirstName.AcceptsTab = false;
            this.txtFirstName.AnimationSpeed = 200;
            this.txtFirstName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFirstName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFirstName.AutoSizeHeight = true;
            this.txtFirstName.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtFirstName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFirstName.BackgroundImage")));
            this.txtFirstName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtFirstName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFirstName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFirstName.BorderColorIdle = System.Drawing.Color.DeepSkyBlue;
            this.txtFirstName.BorderRadius = 10;
            this.txtFirstName.BorderThickness = 2;
            this.txtFirstName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtFirstName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFirstName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFirstName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtFirstName.DefaultText = "";
            this.txtFirstName.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtFirstName.HideSelection = true;
            this.txtFirstName.IconLeft = null;
            this.txtFirstName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFirstName.IconPadding = 10;
            this.txtFirstName.IconRight = null;
            this.txtFirstName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFirstName.Lines = new string[0];
            this.txtFirstName.Location = new System.Drawing.Point(193, 26);
            this.txtFirstName.MaxLength = 32767;
            this.txtFirstName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFirstName.Modified = false;
            this.txtFirstName.Multiline = false;
            this.txtFirstName.Name = "txtFirstName";
            stateProperties17.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.White;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFirstName.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties18.FillColor = System.Drawing.Color.Transparent;
            stateProperties18.ForeColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFirstName.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFirstName.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFirstName.OnIdleState = stateProperties20;
            this.txtFirstName.Padding = new System.Windows.Forms.Padding(3);
            this.txtFirstName.PasswordChar = '\0';
            this.txtFirstName.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtFirstName.PlaceholderText = "Enter First Name";
            this.txtFirstName.ReadOnly = false;
            this.txtFirstName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFirstName.SelectedText = "";
            this.txtFirstName.SelectionLength = 0;
            this.txtFirstName.SelectionStart = 0;
            this.txtFirstName.ShortcutsEnabled = true;
            this.txtFirstName.Size = new System.Drawing.Size(216, 33);
            this.txtFirstName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFirstName.TabIndex = 9;
            this.txtFirstName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFirstName.TextMarginBottom = 0;
            this.txtFirstName.TextMarginLeft = 3;
            this.txtFirstName.TextMarginTop = 1;
            this.txtFirstName.TextPlaceholder = "Enter First Name";
            this.txtFirstName.UseSystemPasswordChar = false;
            this.txtFirstName.WordWrap = true;
            // 
            // cmbGender
            // 
            this.cmbGender.BackColor = System.Drawing.Color.Transparent;
            this.cmbGender.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.cmbGender.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.cmbGender.BorderRadius = 5;
            this.cmbGender.Color = System.Drawing.Color.DeepSkyBlue;
            this.cmbGender.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbGender.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbGender.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbGender.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbGender.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbGender.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbGender.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbGender.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbGender.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbGender.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbGender.FillDropDown = true;
            this.cmbGender.FillIndicator = false;
            this.cmbGender.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbGender.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cmbGender.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.cmbGender.FormattingEnabled = true;
            this.cmbGender.Icon = null;
            this.cmbGender.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbGender.IndicatorColor = System.Drawing.Color.DeepSkyBlue;
            this.cmbGender.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbGender.IndicatorThickness = 2;
            this.cmbGender.IsDropdownOpened = false;
            this.cmbGender.ItemBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.cmbGender.ItemBorderColor = System.Drawing.Color.DeepSkyBlue;
            this.cmbGender.ItemForeColor = System.Drawing.Color.DeepSkyBlue;
            this.cmbGender.ItemHeight = 26;
            this.cmbGender.ItemHighLightColor = System.Drawing.Color.SkyBlue;
            this.cmbGender.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbGender.ItemTopMargin = 3;
            this.cmbGender.Location = new System.Drawing.Point(193, 174);
            this.cmbGender.Name = "cmbGender";
            this.cmbGender.Size = new System.Drawing.Size(216, 32);
            this.cmbGender.TabIndex = 8;
            this.cmbGender.Text = null;
            this.cmbGender.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbGender.TextLeftMargin = 5;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.bunifuLabel4.Location = new System.Drawing.Point(95, 174);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(73, 28);
            this.bunifuLabel4.TabIndex = 7;
            this.bunifuLabel4.Text = "Gender :";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.bunifuLabel3.Location = new System.Drawing.Point(512, 150);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(66, 28);
            this.bunifuLabel3.TabIndex = 5;
            this.bunifuLabel3.Text = "Model : ";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtModel
            // 
            this.txtModel.AcceptsReturn = false;
            this.txtModel.AcceptsTab = false;
            this.txtModel.AnimationSpeed = 200;
            this.txtModel.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtModel.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtModel.AutoSizeHeight = true;
            this.txtModel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtModel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtModel.BackgroundImage")));
            this.txtModel.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtModel.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtModel.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtModel.BorderColorIdle = System.Drawing.Color.DeepSkyBlue;
            this.txtModel.BorderRadius = 10;
            this.txtModel.BorderThickness = 2;
            this.txtModel.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtModel.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtModel.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtModel.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtModel.DefaultText = "";
            this.txtModel.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtModel.HideSelection = true;
            this.txtModel.IconLeft = null;
            this.txtModel.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtModel.IconPadding = 10;
            this.txtModel.IconRight = null;
            this.txtModel.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtModel.Lines = new string[0];
            this.txtModel.Location = new System.Drawing.Point(593, 147);
            this.txtModel.MaxLength = 32767;
            this.txtModel.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtModel.Modified = false;
            this.txtModel.Multiline = false;
            this.txtModel.Name = "txtModel";
            stateProperties21.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.White;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtModel.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties22.FillColor = System.Drawing.Color.Transparent;
            stateProperties22.ForeColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtModel.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtModel.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtModel.OnIdleState = stateProperties24;
            this.txtModel.Padding = new System.Windows.Forms.Padding(3);
            this.txtModel.PasswordChar = '\0';
            this.txtModel.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtModel.PlaceholderText = "Enter Model";
            this.txtModel.ReadOnly = false;
            this.txtModel.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtModel.SelectedText = "";
            this.txtModel.SelectionLength = 0;
            this.txtModel.SelectionStart = 0;
            this.txtModel.ShortcutsEnabled = true;
            this.txtModel.Size = new System.Drawing.Size(216, 33);
            this.txtModel.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtModel.TabIndex = 4;
            this.txtModel.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtModel.TextMarginBottom = 0;
            this.txtModel.TextMarginLeft = 3;
            this.txtModel.TextMarginTop = 1;
            this.txtModel.TextPlaceholder = "Enter Model";
            this.txtModel.UseSystemPasswordChar = false;
            this.txtModel.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.bunifuLabel2.Location = new System.Drawing.Point(518, 87);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(60, 28);
            this.bunifuLabel2.TabIndex = 3;
            this.bunifuLabel2.Text = "Brand : ";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtBrand
            // 
            this.txtBrand.AcceptsReturn = false;
            this.txtBrand.AcceptsTab = false;
            this.txtBrand.AnimationSpeed = 200;
            this.txtBrand.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBrand.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBrand.AutoSizeHeight = true;
            this.txtBrand.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtBrand.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBrand.BackgroundImage")));
            this.txtBrand.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtBrand.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtBrand.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtBrand.BorderColorIdle = System.Drawing.Color.DeepSkyBlue;
            this.txtBrand.BorderRadius = 10;
            this.txtBrand.BorderThickness = 2;
            this.txtBrand.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtBrand.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBrand.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBrand.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtBrand.DefaultText = "";
            this.txtBrand.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            this.txtBrand.HideSelection = true;
            this.txtBrand.IconLeft = null;
            this.txtBrand.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBrand.IconPadding = 10;
            this.txtBrand.IconRight = null;
            this.txtBrand.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBrand.Lines = new string[0];
            this.txtBrand.Location = new System.Drawing.Point(593, 87);
            this.txtBrand.MaxLength = 32767;
            this.txtBrand.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBrand.Modified = false;
            this.txtBrand.Multiline = false;
            this.txtBrand.Name = "txtBrand";
            stateProperties25.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.White;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBrand.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties26.FillColor = System.Drawing.Color.Transparent;
            stateProperties26.ForeColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBrand.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBrand.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(30)))), ((int)(((byte)(54)))));
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBrand.OnIdleState = stateProperties28;
            this.txtBrand.Padding = new System.Windows.Forms.Padding(3);
            this.txtBrand.PasswordChar = '\0';
            this.txtBrand.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtBrand.PlaceholderText = "Enter Brand";
            this.txtBrand.ReadOnly = false;
            this.txtBrand.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBrand.SelectedText = "";
            this.txtBrand.SelectionLength = 0;
            this.txtBrand.SelectionStart = 0;
            this.txtBrand.ShortcutsEnabled = true;
            this.txtBrand.Size = new System.Drawing.Size(216, 33);
            this.txtBrand.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtBrand.TabIndex = 2;
            this.txtBrand.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtBrand.TextMarginBottom = 0;
            this.txtBrand.TextMarginLeft = 3;
            this.txtBrand.TextMarginTop = 1;
            this.txtBrand.TextPlaceholder = "Enter Brand";
            this.txtBrand.UseSystemPasswordChar = false;
            this.txtBrand.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.bunifuLabel1.Location = new System.Drawing.Point(516, 27);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(62, 28);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Car ID :";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // InquiryPage
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(51)))), ((int)(((byte)(73)))));
            this.ClientSize = new System.Drawing.Size(980, 720);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "InquiryPage";
            this.Text = "InquiryPage";
            this.bunifuPanel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dtgAvailableCars)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearch;
        private Bunifu.UI.WinForms.BunifuDataGridView dtgAvailableCars;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel11;
        private Bunifu.UI.WinForms.BunifuTextBox txtContact;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuTextBox txtLastName;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox txtMiddleName;
        private Bunifu.UI.WinForms.BunifuDropdown cmbCarId;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnRent;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox txtFirstName;
        private Bunifu.UI.WinForms.BunifuDropdown cmbGender;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox txtModel;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox txtBrand;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnClear;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnInquire;
    }
}